Repository TEAM-MOAMOA/Frontend, pull requests merged in 2023-08, with the labels that each got.

#17 Feat/home/#16
  src/assets/icon/chattingActiveIcon.svg
  src/assets/icon/chattingNotActiveIcon.svg
  src/assets/icon/distanceIcon.svg
  src/assets/icon/homeActiveIcon.svg
  src/assets/icon/homeNotActiveIcon.svg
  src/assets/icon/profileActiveIcon.svg
  src/assets/icon/profileNotActiveIcon.svg
  src/assets/icon/writingIcon.svg
  src/assets/index.ts
  src/components/common/BottomBar.tsx
  src/components/common/RoundButton.tsx
  src/components/common/TeacherProfile.tsx
  src/components/home/Category.tsx
  src/components/home/CloseDistanceLessonList.tsx
  src/components/home/Header.tsx
  src/components/home/Lesson.tsx
  src/components/home/PopularLessonList.tsx
  src/components/home/PopularTeacherList.tsx
  src/pages/Home.tsx
  src/style/globalStyle.ts
  src/style/theme.ts
Labels: 희정, feat-function, feat-UI

#21 [ style ] 페이지 네이밍 변경
  src/Router.tsx
  src/components/class/ClassAppeal.tsx
  src/components/class/ParticipationInfo.tsx
  src/components/class/ProfileInfo.tsx
  src/components/class/Review.tsx
  src/components/profile/MyApplyClass.tsx
  src/components/profile/MyUploadClass.tsx
  src/components/profile/Profile.tsx
  src/components/profile/ProfileInfo.tsx
  src/pages/Class.tsx
  src/pages/ProfilePage.tsx
Labels: 소은

#22 [ refactor ] 폰트 재변경
  src/components/class/ParticipationInfo.tsx
  src/components/class/ProfileInfo.tsx
  src/pages/Class.tsx
Labels: 소은, Refactor

#23 Feat/profile/#15
  src/assets/image/statusbarImg.svg
  src/assets/image/teacherImg2.svg
  src/assets/index.ts
  src/components/profile/MyApplyClass.tsx
  src/components/profile/MyUploadClass.tsx
  src/components/profile/NoContents.tsx
  src/components/profile/Profile.tsx
  src/pages/ProfilePage.tsx
  src/style/theme.ts
  src/types/WritingData.ts
Labels: 소은, feat-UI

#24 [ style ] margin 수정
  src/components/profile/MyApplyClass.tsx
Labels: 소은, Refactor

#26 [ feat ] 수업 취소하기 버튼 추가
  src/components/class/ParticipationInfo.tsx
  src/components/common/Modal.tsx
Labels: 소은, feat-function, feat-UI

#27 Feat/home/#18
  .firebase/hosting.ZGlzdA.cache
  .firebaserc
  firebase.json
  index.html
  package.json
  src/api/cookie.ts
  src/api/getPopularTeacher.ts
  src/components/common/TeacherProfile.tsx
  src/components/common/TopBar.tsx
  src/components/home/CategoryLesson.tsx
  src/components/home/CloseDistanceLessonList.tsx
  src/components/home/PopularLessonList.tsx
  src/components/home/PopularTeacherList.tsx
  src/components/home/Teacher.tsx
  src/hooks/useGetPopularTeacher.ts
  src/main.tsx
  src/pages/ArtPage.tsx
  src/pages/CloseDistanceTeacherPage.tsx
  src/pages/ExercisePage.tsx
  src/pages/Home.tsx
  src/pages/LanguagePage.tsx
  src/pages/MusicPage.tsx
  src/pages/PopularTeacherPage.tsx
  src/pages/RecommendedTeacherPage.tsx
  src/types/LessonInfo.ts
  yarn.lock
Labels: 희정, feat-function

#32 Feat/alarm/#28
  src/atom/ClassInfo.ts
  src/components/home/CategoryLesson.tsx
Labels: 희정, feat-function

#35 Feat/login/#30
  package.json
  src/firebase.tsx
  src/pages/LoginPage.tsx
Labels: 소은, feat-function

#37 [ feat ] 돌봄이 입장 수업 뷰 구현
  src/components/class/ParentParticipation.tsx
  src/components/class/ParticipationInfo.tsx
  src/components/class/TeacherParticipation.tsx
  src/pages/Class.tsx
Labels: 소은, feat-UI

#40 [ feat ] 로그인 뷰 구현
  src/Router.tsx
  src/assets/icon/googleIcon.svg
  src/assets/icon/kakaoIcon.svg
  src/assets/index.ts
  src/atom/LoginInfo.ts
  src/pages/LoginPage.tsx
  src/style/theme.ts
Labels: 소은, feat-UI

#41 [ refactor ] 로그인 라우터 수정
  src/Router.tsx
  src/pages/LoginPage.tsx
Labels: 소은, Refactor

#42 [ refactor ] 데이터 연결
  src/components/class/ClassAppeal.tsx
  src/components/class/ProfileInfo.tsx
Labels: 소은, Refactor

#43 [ style ] 프로필 이미지 크기 조절
  src/components/class/ProfileInfo.tsx
  src/pages/Class.tsx
Labels: 소은, feat-UI

#45 [ feat ] 회원가입 뷰 구현
  src/Router.tsx
  src/components/user/InputUser.tsx
  src/pages/SignupPage.tsx
  vite.config.ts.timestamp-1691221861234-20e4f99480184.mjs
Labels: 소은, feat-UI

#47 [ feat ] 회원가입 API 연결
  src/components/user/InputUser.tsx
  src/pages/LoginPage.tsx
Labels: 소은, feat-function

#50 [ feat ] 강의 등록 API 연결
  src/pages/Writing.tsx
Labels: 소은, feat-function

#51 [ feat ] 글 작성자 연동
  src/components/class/ParentParticipation.tsx
  src/components/class/ParticipationInfo.tsx
Labels: 소은, feat-function

#52 Feat/alarm/#34
  .firebase/hosting.ZGlzdA.cache
  public/firebase-messaging-sw.js
  src/Router.tsx
  src/assets/icon/allReadIcon.svg
  src/assets/icon/notReadIcon.svg
  src/assets/icon/searchIcon.svg
  src/assets/index.ts
  src/components/alarm/AlarmContainer.tsx
  src/components/alarm/AlarmInfo.tsx
  src/components/common/TopBar.tsx
  src/components/home/Category.tsx
  src/components/home/CloseDistanceLessonList.tsx
  src/components/home/Header.tsx
  src/components/home/PopularLessonList.tsx
  src/components/home/PopularTeacherList.tsx
  src/components/profile/NoContents.tsx
  src/firebase.tsx
  src/pages/Alarm.tsx
  src/pages/AlarmList.tsx
  src/pages/CloseDistanceTeacherPage.tsx
  src/pages/Home.tsx
  src/pages/LanguagePage.tsx
  src/types/AlarmProps.ts
  src/utils/notification.ts
Labels: 희정, feat-function

#54 Feat/location/#53
  src/assets/image/defaultTeacherImg.svg
  src/assets/index.ts
  src/atom/LocationModal.ts
  src/components/user/InputUser.tsx
  src/pages/Home.tsx
Labels: 희정, feat-function

#58 [ refactor ] 신청하기 버튼 재설정
  src/components/class/ParentParticipation.tsx
Labels: 소은, Refactor, Fix

#59 [ feat ] 리뷰 API 연결
  public/img/distance.png
  public/img/profile_default.png
  public/img/star.png
  src/assets/image/defaultProfileImg.svg
  src/assets/index.ts
  src/components/class/Review.tsx
  src/pages/Class.tsx
  src/types/ReviewData.ts
  src/types/ReviewInfo.ts
Labels: 소은, feat-function

#62 [ feat ] 설정 뷰 구현
  src/Router.tsx
  src/assets/icon/arrowIcon.svg
  src/assets/index.ts
  src/atom/ToggleInfo.ts
  src/components/common/Toggle.tsx
  src/pages/Setting.tsx
Labels: 소은, feat-UI

#65 [ refactor ] 더미 데이터 수정
  public/img/profile1.png
  public/img/profile2.png
  public/img/profile_default.png
  src/components/profile/MyApplyClass.tsx
  src/components/profile/Profile.tsx
  src/pages/ProfilePage.tsx
Labels: 소은, Refactor

#68 [ feat ] User 정보 LocalStorage 저장
  package.json
  src/atom/UserInfo.ts
  yarn.lock
Labels: 소은, feat-function

#70 [ feat ] Class 정보 LocalStorage 저장
  src/atom/ClassInfo.ts
Labels: 소은, feat-function
